### PR TITLE
Added Action to Publish Docker Image to Repo

### PR DESCRIPTION
**Pull request by adgsenpai**
# Added GitHub Action to publish Animeflix Image to GitHub Registry 

Did you know your GitHub account comes with its own Docker Registry?

check it out here below
https://github.com/features/packages

Anyway added a script to publish your Docker Image so that the public can pull this image at will!

The GitHub Action can be triggered on `push`, `pull-request`, `manually` as the code updates to keep Docker Images consistent with this repo workflow.

Check the image compiled here @ 
https://github.com/ADGSTUDIOS/animeflix-dockerimage/pkgs/container/animeflix-dockerimage

Best Regards
@adgsenpai

### CODE REVIEW

**Comment by riimuru** [comment]
@adgsenpai LGTM
you should add docker build image badge on the readme as well.

**Comment by adgsenpai** [comment]
@riimuru I have made the above changes you have proposed please check if you are happy with everything now :-)

**Comment by chirag-droid** [comment]
Is it possible to make it so that it only runs after CI workflow is successful?

**Comment by adgsenpai** [comment]
> Is it possible to make it so that it only runs after CI workflow is successful?

Yes I can implement that feature

**Comment by adgsenpai** [comment]
pertaining to > 0b45c27

# Feature is now implemented.

@chirag-droid 

Docker Image Publish now works when CI workflow is successful.

Let me know if any other changes is needed regarding your requirements :-)

**Comment by riimuru** [comment]
@adgsenpai good work overall 👍. but on the docker-publish you're missing the second condition which checks if the workflow_run was a `success`, so you have to add this ` if: ${{ github.event.workflow_run.conclusion == 'success' }}` under the build job.

**Comment by chirag-droid** [comment]
I think it will be more easy to combine this with the ci workflow just in a seperate job

**Pull request closed without merging**
