### PR TITLE
fix: some animes were not found

### PR DESCRIPTION
**Pull request by riimuru**
* This should improve some animes that were previously unavailable, such as Code Geass: Lelouch of the Hangyaku.

### CODE REVIEW

**Comment by riimuru** [comment]
#146

**Comment by riimuru** [comment]
#145

**Comment by chirag-droid** [comment]
This should fix the problem somewhat but there still might be edge cases.

Gogoanime also has release year so matching that would be even better like we do with kitsu.

For now merging this because this is a serious issue.

**Comment by riimuru** [comment]
@chirag-droid That may conflict with the dub version of the anime; I believe the best choice here is to give the user the option of selecting the correct anime if it is wrong.

**Pull request merged**
