### PR TITLE
feat: added playback control shortcuts

### LINKED ISSUE #24: Keyboard shortcuts
Hiya, is it possible for simple keyboard shortcuts for video playback to be added? Such as spacebar to pause/play, right/left arrow to skip forward/backward, up/down arrow for volume and so on. 

It would also be nice if we can choose how many seconds it skips forward/backward to, like between 5 seconds to 15 seconds.

Thanks!

### PR DESCRIPTION
**Pull request by TomRomeo**
This pr implements keyboard shortcuts on the watch page.

| Key | Action |
|-|-|
| k / space | play / pause |
| f | fullscreen |
| Arrow up | Volume up |
| Arrow down | Volume down |
| Arrow left | previous ep |
| Arrow right | next ep |

resolves #24

I can also change `Arrow left` and `Arrow right` to seek forwards and backwards if you feel like that is more appropriate ^^

### CODE REVIEW

**Comment by chirag-droid** [comment]
This doesn't seem to be working quite well. As when you press arrow down the page scrolls down.

VimeJs does provide an api for keyboard control but there seems to be an issue with react and vime-js. The only issue I could find was @vime-js/vime#174, but its dead

**Comment by chirag-droid** [comment]
You can use `e.preventDefault()` to prevent the default behaviour of the keyboard events, but that will prevent all the keyboard events from doing the default task

**Comment by TomRomeo** [comment]
Yeah, I found the issue for vimejs too but since that sadly didn't work, I configured the keyboard shortcuts manually.

What I can do is either e.preventDefault() for `space` and `Arrow up / down` or only register their events in fullscreen, since they won't scroll the page in that case. What do you think makes more sense?

**Comment by chirag-droid** [comment]
I am a bit busy rn but I found the solution that should work in theory.

Put a onclick listener on the document and if the user touches the videoplayer, set it to focus. If the user click anywhere else unfocus it.

Now instead of receiving key events from the whole document, receive only from videoplayer.

**Comment by TomRomeo** [comment]
Alright, I refactored the code.

A few notes:
- I had to keep the event listener on `document`, because it did not get triggered on `videoplayer` if the user was in fullscreen mode. Therefore I also had to keep the `e.preventDefault()` lines.
- enterFullscreen() throws an error when it cannot set the fullscreen via the native browser api but still sets the fullscreen via the video provider, therefore I just 'ignore' the error, resulting in the kinda ugly `.catch(return null)`
- for some reason, setting `outline-none` with tailwind did not work for the videoplayer so I had to use an inline style

Thank you for taking the time out of your busy day to comment on issues.
Let me know if you still want some things changed :)

**Comment by chirag-droid** [comment]
Thanks. Also I didn't know there is something called tabindex. Using tabindex also fixed vimejs not picking up keyboard inputs. So I can change some of the shortcuts to use vimejs api, it will make the code clean.

The keyboard controls are conflicting with existing vimejs controls which weren't previously working.

For now merging this with `keyboard_shortcuts` branch. And here's how I plan the shortcuts.

| Key | Action |
|-|-|
| k / space | play / pause |
| m | mute / unmute |
| n | next episode |
| p | previous episode |
| P | toggle proxy |
| Arrow left / right | seek 5s backward / forward |
| Arrow up / down | Volume up / down |
| f | fullscreen |
| c | caption |
| <, > | Speed up and down |

most of these are implemented by vimejs itself.

**Comment by TomRomeo** [comment]
Nice! I'd be glad to help you with that :)
Do you maybe plan on creating a discord or something so we can work together?

I didn't realize that `tabindex` fixed the vimejs issue. It might be a good idea if you posted that as a comment in the original issue.

**Comment by chirag-droid** [comment]
Oh yes, I would create a discord community.

All the known bugs are removed now from the keyboard shortcuts in #101

**Comment by chirag-droid** [comment]
@TomRomeo here is the discord https://discord.gg/4UPU8etvae

**Pull request merged**
