### PR TITLE
Feat: back to proxy & slug search improvements

### PR DESCRIPTION
**Pull request by riimuru**
- Many animes will not load (e.g: Daily Lives of High School Boys) without a proxy, so I believe it is best to use it.
 - Some anime titles contain unicode characters, which should be replaced with a space.

### CODE REVIEW

**Comment by chirag-droid** [comment]
So the anime `11843` is working for me. 

The [stream url](https://www10.gogocdn.stream/videos/hls/QpuFXt2bViNdzGX-HS9tiA/1651360919/9879/e1966e9fd9412fa92b7df62e69a0438a/ep.1.1645242517.m3u8) is working for me without proxying.

node-version `16.5.0` and region - India

**Comment by chirag-droid** [comment]
I think we should probably have a automated testing at this point.

**Comment by chirag-droid** [comment]
I need to confirm if we would need a proxy. But we do need to escape out unicodes.

I removed proxy because it was causing some problems

**Comment by riimuru** [comment]
> I think we should probably have a automated testing at this point.

I agree

> I need to confirm if we would need a proxy. But we do need to escape out unicodes.
> I removed proxy because it was causing some problems

What kind of problems was it causing?

**Comment by riimuru** [comment]
> So the anime `11843` is working for me.
> 
> The [stream url](https://www10.gogocdn.stream/videos/hls/QpuFXt2bViNdzGX-HS9tiA/1651360919/9879/e1966e9fd9412fa92b7df62e69a0438a/ep.1.1645242517.m3u8) is working for me without proxying.
> 
> node-version `16.5.0` and region - India

You're using a streaming url from the sources_bk array, which is for hls (some of which don't require any proxy). This is the [streaming url](https://vidstreamingcdn.com/cdn26/0a2f6f1ada14f501270e5899b4d99793/EP.1.v1.1639306318.720p.mp4) that is picked, and it doen't work without proxy.

**Comment by chirag-droid** [comment]
Oh wait I am getting this [url](https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/6304318289001/6f145d0c-a121-47ff-a5a9-43af0e7e1cff/6s/master.m3u8?fastly_token=NjI2ZGZjZDdfYTAxZjc1NTdlOTFmNjBmOTI5ZDExNjkwNWY3MjNlZTQ2MDExNDc2NTA5NWIzYmMzNWRkM2QwNmQ4OTU5ZjJjYQ%3D%3D) for anime `99147`

**Comment by chirag-droid** [comment]
I noticed the urls in sources list work without Referrer and the one in sources_bk don't. And they aren't correctly marked as mp4 and hls

**Comment by chirag-droid** [comment]
I noticed the urls in sources list work without Referrer and the one in sources_bk don't. And they aren't correctly marked as mp4 and hls

**Comment by chirag-droid** [comment]
I am using urls from sources. they work just fine without referer although most of the time they are hls

**Comment by chirag-droid** [comment]
I am using urls from sources. they work just fine without referer although most of the time they are hls

**Comment by riimuru** [comment]
> Oh wait I am getting this [url](https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/6304318289001/6f145d0c-a121-47ff-a5a9-43af0e7e1cff/6s/master.m3u8?fastly_token=NjI2ZGZjZDdfYTAxZjc1NTdlOTFmNjBmOTI5ZDExNjkwNWY3MjNlZTQ2MDExNDc2NTA5NWIzYmMzNWRkM2QwNmQ4OTU5ZjJjYQ%3D%3D) for anime `99147`

yes thats right, i choose the file from sources_bk thats why

**Comment by riimuru** [comment]
> I noticed the urls in sources list work without Referrer and the one in sources_bk don't. And they aren't correctly marked as mp4 and hls

Yes, sometimes they're not correctly marked, but not all urls from sources list work without referer

**Comment by riimuru** [comment]
@chirag-droid whats the urls sources list that are you getting for anime `11843`?

**Comment by chirag-droid** [comment]
@riimuru I am getting this

```js
{
  Referer: 'https://goload.pro/streaming.php?id=OTg3OQ==&title=Danshi+Koukousei+no+Nichijou+Episode+1&typesub=SUB',
  sources: [
    {
      file: 'https://www10.gogocdn.stream/videos/hls/oQR66lvTvN8qvkI0JA-Mkw/1651373600/9879/e1966e9fd9412fa92b7df62e69a0438a/ep.1.1645242517.m3u8',
      label: 'hls P',
      type: 'hls'
    }
  ],
  sources_bk: [
    {
      file: 'https://www10.gogocdn.stream/videos/hls/oQR66lvTvN8qvkI0JA-Mkw/1651373600/9879/e1966e9fd9412fa92b7df62e69a0438a/ep.1.1645242517.m3u8',
      label: 'hls P',
      type: 'hls'
    }
  ]
}
```

**Comment by riimuru** [comment]
@chirag-droid this is what i get
```js
{
  Referer: 'https://goload.pro/streaming.php?id=OTg3OQ==&title=Danshi+Koukousei+no+Nichijou+Episode+1&typesub=SUB',
  sources: [
    {
      file: 'https://vidstreamingcdn.com/cdn26/0a2f6f1ada14f501270e5899b4d99793/EP.1.v1.1639306318.360p.mp4',
      label: '360 P',
      type: 'mp4'
    },
    {
      file: 'https://vidstreamingcdn.com/cdn26/0a2f6f1ada14f501270e5899b4d99793/EP.1.v1.1639306318.480p.mp4',
      label: '480 P',
      type: 'mp4'
    },
    {
      file: 'https://vidstreamingcdn.com/cdn26/0a2f6f1ada14f501270e5899b4d99793/EP.1.v1.1639306318.720p.mp4',
      label: '720 P',
      type: 'mp4'
    },
    {
      file: 'https://vidstreamingcdn.com/cdn26/0a2f6f1ada14f501270e5899b4d99793/EP.1.v1.1639306318.1080p.mp4',
      label: '1080 P',
      type: 'mp4'
    },
    {
      file: 'https://vidstreamingcdn.com/cdn26/0a2f6f1ada14f501270e5899b4d99793/EP.1.v1.1639306318.720p.mp4',
      label: 'Auto',
      default: 'true',
      type: 'mp4'
    }
  ],
  sources_bk: [
    {
      file: 'https://www10.gogocdn.stream/videos/hls/f0Ofwoy73pvvud0k1l_akA/1651374999/9879/e1966e9fd9412fa92b7df62e69a0438a/ep.1.1645242517.m3u8',
      label: 'hls P',
      type: 'hls'
    }
  ]
}
```

**Comment by riimuru** [comment]
I guess the url sources depend on where you live.

**Comment by dhvitOP** [comment]
Sometimes when sources_bk array's hls url doesn't work, sources array also contains another hls url for backup if sources_bk one have a problem.

**Comment by chirag-droid** [comment]
Hey, so for now I have raised a new issue #87 regarding this, we can discuss this there. I am not entirely sure what's causing the issue. For now can we just escape unicodes?

**Comment by chirag-droid** [comment]
What site do you get redirected to when you visit https://gogoanime.film/ ? For me its https://gogoanime.gg

**Comment by chirag-droid** [comment]
Ok, I am merging this for now then

**Comment by riimuru** [comment]
> @riimuru What site do you get redirected to when you visit https://gogoanime.film/ ? For me its https://gogoanime.gg

Yes i get redirected to gogoanime.gg as well.

**Pull request merged**
